#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_APPICON                             100
#define IDI_APPICON_ON                          101
#define IDI_APPICON_ONOFF                       102
#define IDI_APPICON_OFF                         103
#define IDI_APACHE                              104
#define IDI_MARIA                               105
#define IDI_PHP                                 106
#define IDI_COMPOSER                            107
#define IDI_PMA                                 108
#define IDI_GCC                                 109
#define IDI_RES                                 110
#define IDM_CONTEXTMENU                         115
#define IDD_APP_DIALOG                          116
#define IDD_THANKS                              128
#define IDD_ABOUT                               129
#define IDR_AVI                                 131
#define IDC_RADIO1                              40000
#define IDC_RADIO2                              40001
#define IDC_RADIO3                              40002
#define IDC_ROOTPATH                            40004
#define IDD_ANIMATION                           40005
#define IDC_CHECK_AUTO_APACHE                   40006
#define IDC_CHECK_AUTO_MARIA                    40007
#define IDC_USEHTTPS                            40008
#define IDC_USERPATH                            40009
#define IDC_CHECK_EXIT_ALL                      40010
#define IDC_CHECK_CLEAR_LOGS                    40011
#define IDC_INSTALLCA                           40012
#define IDC_APACHE_ERROR                        40013
#define IDC_ABOUT                               40014
#define IDC_EDIT_DOC_ROOT                       40015
#define IDC_SET_DOCROOT                         40016
#define IDC_APACHE_ACCESS                       40017
#define IDC_PHP_ERROR                           40019
#define IDC_MARIA_ERROR                         40020
#define IDC_COMPOSER_V                          40021
#define IDC_LOGO                                40022
#define IDC_BROWSE                              40023
#define IDC_REFRESH                             40024
#define IDC_THANKS                              40025
#define IDC_VHOSTS                              40026
#define IDC_PMA_V                               40027
#define IDM_START_ALL                           40028
#define IDC_PHP_INFO                            40029
#define IDM_RESET_ALL                           40030
#define IDC_QUIT                                40031
#define IDC_PHPMYADMIN                          40032
#define IDC_APACHE_START                        40033
#define IDC_MARIA_START                         40034
#define IDC_APACHE_RESET                        40035
#define IDC_MARIA_RESET                         40036
#define IDC_MARIA_STATIC                        40037
#define IDC_APACHE_STATIC                       40038
#define IDC_PHP_V                               40039
#define IDC_APACHE_V                            40040
#define IDC_MARIA_V                             40041
